# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: enabled
dist: xenial
cache:
  - packages
  - ccache
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev
      - libudunits2-dev

## see https://github.com/hypertidy/vapour/blob/master/.travis.yml#L29


after_success:
  - Rscript -e 'covr::codecov()'
