#' Generate a ggplot2 representation of an SOmap object
#'
#' Note: this function is still experimental! Use at your own risk.
#'
#' @param x SOmap or SOauto_map: object as returned by \code{SOmap}, \code{SOmap2}, or \code{SOauto_map}
#'
#' @return A ggplot object
#'
#' @examples
#' \dontrun{
#'   p <- SOmap2(Trim = -45, IWC = TRUE, IWClab = TRUE, Grats = TRUE, fronts = TRUE,
#'               MPA = TRUE, MPAlab = TRUE)
#'   SOgg(p)
#' }
#'
#' @export
SOgg <- function(x) {
    if (inherits(x, "SOmap")) {
        SOgg_notauto(x)
    } else if (inherits(x, "SOauto_map")) {
        SOgg_auto(x)
    } else {
        stop("x must be an SOmap/SOauto_map object as generated by SOmap, SOmap2, or SOauto_map")
    }
}

SOgg_notauto <- function(x) {
    if (!inherits(x, "SOmap")) stop("x must be an SOmap object as generated by SOmap or SOmap2")
    myext <- extent(x$target)
    ## plot bathymetry
    bdf <- raster::as.data.frame(raster::trim(SOmap::latmask(x$bathy$plotargs$x, latitude = x$trim)), xy = TRUE)
    names(bdf)[3] <- "Depth"
    p <- ggplot(data = bdf, aes_string(x = "x", y = "y")) + geom_raster(aes_string(fill = "Depth"))
    p <- p + coord_sf(default = TRUE) ## default = TRUE makes this the default coordinate system for geom_sf objects
    p <- p + scale_fill_gradientn(colours = x$bathy$plotargs$col, na.value = "#FFFFFF00", guide = FALSE)
    if (!is.null(x$bathy_legend)) {
        suppressMessages(thecolors <- fortify(x$bathy_legend$plotargs$legend$legend))
        ## exclude the last two entries here, they are the outer (long) borders
        theticks <- x$bathy_legend$plotargs$ticks$ticks
        theticks <- theticks[seq_len(nrow(theticks)-2), ]
        suppressMessages(theticks <- fortify(theticks))
        suppressMessages(themask <- fortify(x$bathy_legend$plotargs$graticules$graticules))
        thecolors$cols <- as.numeric(thecolors$id)
        p <- p + geom_line(data = theticks, aes_string(x = "long", y = "lat", group = "group"), col = x$bathy_legend$plotargs$ticks$col, size = 1)
        p <- p + geom_polygon(data = thecolors, aes_string(x = "long", y = "lat", group = "group"),  fill = NA, col = x$bathy_legend$plotargs$ticks$col, size = 1)

        for (ii in seq_along(x$bathy_legend$plotargs$legend$col)) {
            p <- p + geom_polygon(data = thecolors[thecolors$cols == ii, ], aes_string(x = "long", y = "lat", group = "group"), fill = x$bathy_legend$plotargs$legend$col[ii], col = NA)
        }
        p <- p + geom_text(data = as.data.frame(x$bathy_legend$plotargs$labels$data), aes_string(x = "lon", y = "lat", label = "a"), size = 2)
    }

    ## buffer to use for cropping things back to our extent of interest
    buf <- make_buf(x$trim+2, x$projection)

    if (!is.null(x$coastline)) {
        ## the coastline data has to be trimmed to our northernmost latitude
        ## masking (using e.g. x$bathy_legend$mask$graticule) is likely to be problematic because of z-ordering
        ## TODO check that this trimming is robust
        this <- suppressWarnings(sf::st_intersection(buf, x$coastline$plotargs$x))
        p <- p + geom_sf(data = this, fill = x$coastline$plotargs$col, col = x$coastline$plotargs$border, inherit.aes = FALSE)
    }


    ## fronts
    if (!is.null(x$fronts)) {
        this <- x$fronts$plotargs$x##sf::st_as_sf(x$fronts$plotargs$x)
        this <- suppressWarnings(sf::st_intersection(buf, this))
        thiscol <- rep(x$fronts$plotargs$col, ceiling(nrow(this)/length(x$fronts$plotargs$col)))
        thiscol <- thiscol[seq_len(nrow(this))]
        p <- p + geom_sf(data = this, col = thiscol, inherit.aes = FALSE)
    }
    ## Graticule grid
    if (!is.null(x$graticule)) {
        this <- fortify(x$graticule$plotargs$x)
        this <- this[this$long >= myext[1] & this$long <= myext[2] & this$lat >= myext[3] & this$lat <= myext[4], ]
        ##raster::plot(x$graticule[[1]]$data, add = TRUE, col = x$graticule[[1]]$col, lty = x$graticule[[1]]$lty)
        p <- p + geom_path(data = this, aes_string(x = "long", y = "lat", group = "group"), col = x$graticule$plotargs$col, linetype = x$graticule$plotargs$lty)
        if (!is.null(x$graticule$labels)) {
            this <- as.data.frame(x$graticule$labels$plotargs$x)
            this <- this[this$x >= myext[1] & this$x <= myext[2] & this$y >= myext[3] & this$y <= myext[4], ]
            p <- p + geom_text(data = this, aes_string(label = "lab"), parse = TRUE, col = x$graticule$labels$plotargs$col)##, cex = x$graticule$labels$plotargs$cex)
            ## can't use cex on that, it gets translated to a size aesthetic, which is an absolute not relative size
        }
    }

    p <- p + labs() + theme(axis.title = element_blank(),
                            axis.text.x = element_blank(), axis.ticks.x = element_blank(),
                            axis.text.y = element_blank(), axis.ticks.y = element_blank(),
                            panel.border = element_blank(),
                            panel.background = element_blank())

    if (!is.null(x$ccamlr_statistical_areas)) {
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_statistical_areas$plotargs$x)))
        p <- p + geom_sf(data = this, col = x$ccamlr_statistical_areas$plotargs$border,  inherit.aes = FALSE, fill = NA)#fill = x$ccamlr_statistical_areas$plotargs$col)
        if (!is.null(x$ccamlr_statistical_areas$labels)) {
            this <- x$ccamlr_statistical_areas$labels[[1]]$plotargs$x
            that <- x$ccamlr_statistical_areas$labels[[2]]$plotargs$x
            then <- x$ccamlr_statistical_areas$labels[[3]]$plotargs$x

            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(this)))
            that <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(that)))
            then <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(then)))

            p <- p + geom_sf_text(data = as.data.frame(this), aes_string(label = "LongLabel"), parse = FALSE, col = x$ccamlr_statistical_areas$labels[[1]]$plotargs$col, size = 2, inherit.aes = FALSE)+
                geom_sf_text(data = as.data.frame(that), aes_string(label = "LongLabel"), parse = FALSE, col = x$ccamlr_statistical_areas$labels[[2]]$plotargs$col, size = 2, inherit.aes = FALSE)+
                geom_sf_text(data = as.data.frame(then), aes_string(label = "LongLabel"), parse = FALSE, col = x$ccamlr_statistical_areas$labels[[3]]$plotargs$col, size = 2, inherit.aes = FALSE)##, cex = x$mpa$labels$cex, pos = x$mpa$labels$pos, offset = x$mpa$labels$offset)
        }
    }

    if (!is.null(x$ccamlr_ssru)) {
        if (is.null(x$ccamlr_ssru$plotargs$col)) x$ccamlr_ssru$plotargs$col <- NA
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_ssru$plotargs$x)))
        p <- p + geom_sf(data = this, col = x$ccamlr_ssru$plotargs$border, fill = x$ccamlr_ssru$plotargs$col, inherit.aes = FALSE)
        if (!is.null(x$ccamlr_ssru$labels)) {
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_ssru$labels$plotargs$x)))
            p <- p + geom_sf_text(data = as.data.frame(this), aes_string(label = as.character("Name")), parse = FALSE, col = x$ccamlr_ssru$labels$plotargs$col, size = 2, inherit.aes = FALSE)##, cex = x$mpa$labels$cex, pos = x$mpa$labels$pos, offset = x$mpa$labels$offset)
        }
    }


    if (!is.null(x$ccamlr_ssmu)) {
        if (is.null(x$ccamlr_ssmu$plotargs$col)) x$ccamlr_ssmu$plotargs$col <- NA
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_ssmu$plotargs$x)))
        p <- p + geom_sf(data = this, col = x$ccamlr_ssmu$plotargs$border, fill = x$ccamlr_ssmu$plotargs$col, inherit.aes = FALSE)
        if (!is.null(x$ccamlr_ssmu$labels)) {
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_ssmu$plotargs$x)))
            p <- p + geom_sf_text(data = as.data.frame(this), aes_string(label = as.character("ShortLabel")), parse = FALSE, col = x$ccamlr_ssmu$plotargs$border, size = 2, inherit.aes = FALSE)##, cex = x$mpa$labels$cex, pos = x$mpa$labels$pos, offset = x$mpa$labels$offset)
        }
    }

    if (!is.null(x$iwc)) {
        pidx <- seq_along(x$iwc)
        if (!is.null(names(x$iwc))) pidx <- pidx[!names(x$iwc) %in% c("labels")] ## not labels here
        if (length(pidx) > 0) {
            this <- do.call(rbind, lapply(pidx, function(z) { out <- as.data.frame(x$iwc[[z]]$plotargs$x); out$id <- z; out}))
            names(this) <- c("x", "y", "id")
            p <- p + geom_path(data = this, aes_string(x = "x", y = "y", group = "id"), col = x$iwc[[pidx[1]]]$plotargs$col, inherit.aes = FALSE)
        }
        if (!is.null(x$iwc$labels)) {
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$iwc$labels$plotargs$x)))
            p <- p + geom_sf_text(data = as.data.frame(this), aes_string(label = "a.1"), parse = FALSE, col = x$iwc$labels$plotargs$col, size = 2, inherit.aes = FALSE)
        }
    }

    if (!is.null(x$research_blocks)) {
        if (is.null(x$research_blocks$plotargs$col)) x$research_blocks$plotargs$col <- NA
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$research_blocks$plotargs$x)))
        p <- p + geom_sf(data = this, col = x$research_blocks$plotargs$border, fill = x$research_blocks$plotargs$col, inherit.aes = FALSE)
        if (!is.null(x$research_blocks$labels)) {
            this <- x$research_blocks$labels$plotargs$x
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(this)))
            p <- p + geom_sf_text(data = as.data.frame(this), aes_string(label = as.character("GAR_Short_")), parse = FALSE, col = x$research_blocks$labels$plotargs$col, size = 2, inherit.aes = FALSE)
        }
    }

    if (!is.null(x$sprfmo_research_blocks)) {
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$sprfmo_research_blocks[[1]]$plotargs$x)))
        that <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$sprfmo_research_blocks[[2]]$plotargs$x)))
        p <- p + geom_sf(data = this, col = x$sprfmo_research_blocks[[1]]$plotargs$col,  inherit.aes = FALSE) + geom_sf(data = that, col = x$sprfmo_research_blocks[[2]]$plotargs$col,  inherit.aes = FALSE)

    }

    if (!is.null(x$eez)) {
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$eez$plotargs$x)))
        p <- p + geom_sf(data = this, col = x$eez$plotargs$border, fill = x$eez$plotargs$col, inherit.aes = FALSE)
        if (!is.null(x$eez$labels)) {
            this <- x$eez$labels$plotargs$x
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(this)))
            p <- p + geom_sf_text(data = this, aes_string(label = "ShortLabel"), parse = FALSE,size = 2, col = x$eez$labels$plotargs$col, inherit.aes = FALSE)##, cex = x$eez$labels$cex, pos = x$eez$labels$pos, offset = x$eez$labels$offset)
        }
    }

    if (!is.null(x$mpa)) {
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$mpa$plotargs$x)))
        p <- p + geom_sf(data = this, col = x$mpa$plotargs$border, fill = x$mpa$plotargs$col, inherit.aes = FALSE)
        if (!is.null(x$mpa$labels)) {
            this <- x$mpa$labels$plotargs$x
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(this)))
            p <- p + geom_sf_text(data = as.data.frame(this), aes_string(label = "ShortLabel"), parse = TRUE, col = x$mpa$labels$plotargs$col, size = 2, inherit.aes = FALSE)##, cex = x$mpa$labels$cex, pos = x$mpa$labels$pos, offset = x$mpa$labels$offset)
        }
    }

    if (!is.null(x$ccamlr_planning_domains)) {
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_planning_domains$plotargs$x)))
        ## TODO fix that intersection, is slow because of complexity of coastline
        p <- p + geom_sf(data = this, col = x$ccamlr_planning_domains$plotargs$border, fill = x$ccamlr_planning_domains$plotargs$col, inherit.aes = FALSE)
        if (!is.null(x$ccamlr_planning_domains$labels)) {
            ## this is horrible code
            crds <- as.data.frame(sp::coordinates(x$ccamlr_planning_domains$labels[[1]]$plotargs$x))
            names(crds) <- c("x", "y")
            crds$lab <- x$ccamlr_planning_domains$labels[[1]]$plotargs$x$labs
            p <- p + geom_text(data = crds, aes_string(x = "x", y = "y", label = "lab"), parse = FALSE, col = x$ccamlr_planning_domains$labels[[1]]$plotargs$col, inherit.aes = FALSE, hjust = 0.5, vjust = 1)
            crds$lab <- x$ccamlr_planning_domains$labels[[2]]$plotargs$x$labs1
            p <- p + geom_text(data = crds, aes_string(x = "x", y = "y", label = "lab"), parse = FALSE, col = x$ccamlr_planning_domains$labels[[2]]$plotargs$col, inherit.aes = FALSE, hjust = 0.5, vjust = 0)
            crds$lab <- x$ccamlr_planning_domains$labels[[3]]$plotargs$x$labs2
            p <- p + geom_text(data = crds, aes_string(x = "x", y = "y", label = "lab"), parse = FALSE, col = x$ccamlr_planning_domains$labels[[3]]$plotargs$col, inherit.aes = FALSE, hjust = 0.5, vjust = 1)
            crds$lab <- x$ccamlr_planning_domains$labels[[4]]$plotargs$x$labs7
            p <- p + geom_text(data = crds, aes_string(x = "x", y = "y", label = "lab"), parse = FALSE, col = x$ccamlr_planning_domains$labels[[4]]$plotargs$col, inherit.aes = FALSE, hjust = 0, vjust = 0.5)
            ## the hjust/vjust settings here are a rough attempt to position the labels more nicely
            ## needs work
        }
    }

    if (!is.null(x$border)) {
        suppressMessages(this <- fortify(x$border$plotargs$x))
        this$col <- (as.numeric(this$id) %% length(x$border$plotargs$col)) + 1
        for (ii in seq_along(x$border$plotargs$col)) {
            p <- p + geom_polygon(data = this[this$col == ii, ], aes_string(x = "long", y = "lat", group = "group"), fill = x$border$plotargs$col[ii], col = "black")
        }
    }
    p
}


## NOTE, parse args to geom_text and geom_sf_text seem fragile, need better user control


## refactored version

SOgg2 <- function(x) {
    if (inherits(x, "SOmap")) {
        SOgg2_notauto(x)
    } else if (inherits(x, "SOauto_map")) {
        stop("auto not implemented yet") ##SOgg2_auto(x)
    } else {
        stop("x must be an SOmap/SOauto_map object as generated by SOmap, SOmap2, or SOauto_map")
    }
}

SOgg2_notauto <- function(x) {
    if (!inherits(x, "SOmap")) stop("x must be an SOmap object as generated by SOmap or SOmap2")
    myext <- extent(x$target)
    ## plot bathymetry
    bdf <- raster::as.data.frame(raster::trim(SOmap::latmask(x$bathy$plotargs$x, latitude = x$trim)), xy = TRUE)
    names(bdf)[3] <- "Depth"

    out <- x[intersect(names(x), c("projection", "target", "straight", "trim"))]
    out$init <- list(as_plotter(plotfun = "ggplot2::ggplot", plotargs = list(data = bdf, mapping = aes_string(x = "x", y = "y"))))
    out$bathy <- list(as_plotter(plotfun = "ggplot2::geom_raster", plotargs = list(mapping = aes_string(fill = "Depth"))))
    out$coord <- as_plotter(plotfun = coord_sf, plotargs = list(default = TRUE))
    out$plot_sequence <- c("init", "bathy", "coord")

    out$scale_fill <- as_plotter(plotfun = "ggplot2::scale_fill_gradientn", plotargs = list(colours = x$bathy$plotargs$col, na.value = "#FFFFFF00", guide = FALSE))
    out$plot_sequence <- c(out$plot_sequence, "scale_fill")

    if (!is.null(x$bathy_legend)) {
        suppressMessages(thecolors <- fortify(x$bathy_legend$plotargs$legend$legend))
        ## exclude the last two entries here, they are the outer (long) borders
        theticks <- x$bathy_legend$plotargs$ticks$ticks
        theticks <- theticks[seq_len(nrow(theticks)-2), ]
        suppressMessages(theticks <- fortify(theticks))
        suppressMessages(themask <- fortify(x$bathy_legend$plotargs$graticules$graticules))
        thecolors$cols <- as.numeric(thecolors$id)
        out$bathy_legend <- list(
            as_plotter(plotfun = "ggplot2::geom_line", plotargs = list(data = theticks, aes_string(x = "long", y = "lat", group = "group"), col = x$bathy_legend$plotargs$ticks$col, size = 1)),
            as_plotter(plotfun = "ggplot2::geom_polygon", plotargs = list(data = thecolors, aes_string(x = "long", y = "lat", group = "group"),  fill = NA, col = x$bathy_legend$plotargs$ticks$col, size = 1)))
        out$bathy_legend <- c(out$bathy_legend, lapply(seq_along(x$bathy_legend$plotargs$legend$col), function(ii) as_plotter(plotfun = "ggplot2::geom_polygon", plotargs = list(data = thecolors[thecolors$cols == ii, ], aes_string(x = "long", y = "lat", group = "group"), fill = x$bathy_legend$plotargs$legend$col[ii], col = NA))))
        out$bathy_legend <- c(out$bathy_legend, list(as_plotter(plotfun = "ggplot2::geom_text", plotargs = list(data = as.data.frame(x$bathy_legend$plotargs$labels$data), aes_string(x = "lon", y = "lat", label = "a"), size = 2))))
        out$plot_sequence <- c(out$plot_sequence, "bathy_legend")
    }

    ## buffer to use for cropping things back to our extent of interest
    buf <- make_buf(x$trim+2, x$projection)

    if (!is.null(x$coastline)) {
        ## the coastline data has to be trimmed to our northernmost latitude
        ## masking (using e.g. x$bathy_legend$mask$graticule) is likely to be problematic because of z-ordering
        ## TODO check that this trimming is robust
        this <- suppressWarnings(sf::st_intersection(buf, x$coastline$plotargs$x))
        out$coastline <- as_plotter(plotfun = "ggplot2::geom_sf", plotargs = list(data = this, fill = x$coastline$plotargs$col, col = x$coastline$plotargs$border, inherit.aes = FALSE))
        out$plot_sequence <- c(out$plot_sequence, "coastline")
    }

    ## fronts
    if (!is.null(x$fronts)) {
        this <- x$fronts$plotargs$x
        this <- suppressWarnings(sf::st_intersection(buf, this))
        thiscol <- rep(x$fronts$plotargs$col, ceiling(nrow(this)/length(x$fronts$plotargs$col)))
        thiscol <- thiscol[seq_len(nrow(this))]
        out$fronts <- as_plotter(plotfun = "ggplot2::geom_sf", plotargs = list(data = this, col = thiscol, inherit.aes = FALSE))
        out$plot_sequence <- c(out$plot_sequence, "fronts")
    }

    ## Graticule grid
    if (!is.null(x$graticule)) {
        this <- fortify(x$graticule$plotargs$x)
        this <- this[this$long >= myext[1] & this$long <= myext[2] & this$lat >= myext[3] & this$lat <= myext[4], ]
        out$graticule <- list(as_plotter(plotfun = "ggplot2::geom_path", plotargs = list(data = this, aes_string(x = "long", y = "lat", group = "group"), col = x$graticule$plotargs$col, linetype = x$graticule$plotargs$lty)))
        if (!is.null(x$graticule$labels)) {
            this <- as.data.frame(x$graticule$labels$plotargs$x)
            this <- this[this$x >= myext[1] & this$x <= myext[2] & this$y >= myext[3] & this$y <= myext[4], ]
            out$graticule <- c(out$graticule, list(as_plotter(plotfun = "ggplot2::geom_text", plotargs = list(data = this, aes_string(label = "lab"), parse = TRUE, col = x$graticule$labels$plotargs$col))))##, cex = x$graticule$labels$plotargs$cex)
            ## can't use cex on that, it gets translated to a size aesthetic, which is an absolute not relative size
        }
        out$plot_sequence <- c(out$plot_sequence, "graticule")
    }

    out$axis_labels <- as_plotter(plotfun = "ggplot2::labs", plotargs = list())
    out$plot_sequence <- c(out$plot_sequence, "axis_labels")
    out$theme <- as_plotter(plotfun = "ggplot2::theme", plotargs = list(axis.title = element_blank(),
                            axis.text.x = element_blank(), axis.ticks.x = element_blank(),
                            axis.text.y = element_blank(), axis.ticks.y = element_blank(),
                            panel.border = element_blank(),
                            panel.background = element_blank()))
    out$plot_sequence <- c(out$plot_sequence, "theme")


    if (!is.null(x$ccamlr_statistical_areas)) {
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_statistical_areas$plotargs$x)))
        out$ccamlr_statistical_areas <- list(as_plotter(plotfun = "ggplot2::geom_sf", plotargs = list(data = this, col = x$ccamlr_statistical_areas$plotargs$border,  inherit.aes = FALSE, fill = NA)))#fill = x$ccamlr_statistical_areas$plotargs$col)
        if (!is.null(x$ccamlr_statistical_areas$labels)) {
            this <- x$ccamlr_statistical_areas$labels[[1]]$plotargs$x
            that <- x$ccamlr_statistical_areas$labels[[2]]$plotargs$x
            then <- x$ccamlr_statistical_areas$labels[[3]]$plotargs$x

            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(this)))
            that <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(that)))
            then <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(then)))

            out$ccamlr_statistical_areas <- c(out$ccamlr_statistical_areas,
                                 list(as_plotter(plotfun = "ggplot2::geom_sf_text", plotargs = list(data = as.data.frame(this), aes_string(label = "LongLabel"), parse = FALSE, col = x$ccamlr_statistical_areas$labels[[1]]$plotargs$col, size = 2, inherit.aes = FALSE)),
                                      as_plotter(plotfun = "ggplot2::geom_sf_text", plotargs = list(data = as.data.frame(that), aes_string(label = "LongLabel"), parse = FALSE, col = x$ccamlr_statistical_areas$labels[[2]]$plotargs$col, size = 2, inherit.aes = FALSE)),
                                      as_plotter(plotfun = "ggplot2::geom_sf_text", plotargs = list(data = as.data.frame(then), aes_string(label = "LongLabel"), parse = FALSE, col = x$ccamlr_statistical_areas$labels[[3]]$plotargs$col, size = 2, inherit.aes = FALSE))))##, cex = x$mpa$labels$cex, pos = x$mpa$labels$pos, offset = x$mpa$labels$offset)
        }
        out$plot_sequence <- c(out$plot_sequence, "ccamlr_statistical_areas")
    }


    if (!is.null(x$ccamlr_ssru)) {
        if (is.null(x$ccamlr_ssru$plotargs$col)) x$ccamlr_ssru$plotargs$col <- NA
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_ssru$plotargs$x)))
        out$ccamlr_ssru <- list(as_plotter(plotfun = "ggplot2::geom_sf", plotargs = list(data = this, col = x$ccamlr_ssru$plotargs$border, fill = x$ccamlr_ssru$plotargs$col, inherit.aes = FALSE)))
        if (!is.null(x$ccamlr_ssru$labels)) {
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_ssru$labels$plotargs$x)))
            out$ccamlr_ssru <- c(out$ccamlr_ssru, list(as_plotter(plotfun = "ggplot2::geom_sf_text", plotargs = list(data = as.data.frame(this), aes_string(label = as.character("Name")), parse = FALSE, col = x$ccamlr_ssru$labels$plotargs$col, size = 2, inherit.aes = FALSE))))##, cex = x$mpa$labels$cex, pos = x$mpa$labels$pos, offset = x$mpa$labels$offset)
        }
        out$plot_sequence <- c(out$plot_sequence, "ccamlr_ssru")
    }

    if (!is.null(x$ccamlr_ssmu)) {
        if (is.null(x$ccamlr_ssmu$plotargs$col)) x$ccamlr_ssmu$plotargs$col <- NA
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_ssmu$plotargs$x)))
        out$ccamlr_ssmu <- list(as_plotter(plotfun = "ggplot2::geom_sf", plotargs = list(data = this, col = x$ccamlr_ssmu$plotargs$border, fill = x$ccamlr_ssmu$plotargs$col, inherit.aes = FALSE)))
        if (!is.null(x$ccamlr_ssmu$labels)) {
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_ssmu$plotargs$x)))
            out$ccamlr_ssmu <- c(out$ccamlr_ssmu, list(as_plotter(plotfun = "ggplot2::geom_sf_text", plotargs = list(data = as.data.frame(this), aes_string(label = as.character("ShortLabel")), parse = FALSE, col = x$ccamlr_ssmu$plotargs$border, size = 2, inherit.aes = FALSE))))##, cex = x$mpa$labels$cex, pos = x$mpa$labels$pos, offset = x$mpa$labels$offset)
        }
        out$plot_sequence <- c(out$plot_sequence, "ccamlr_ssmu")
    }

    if (!is.null(x$iwc)) {
        pidx <- seq_along(x$iwc)
        if (!is.null(names(x$iwc))) pidx <- pidx[!names(x$iwc) %in% c("labels")] ## not labels here
        if (length(pidx) > 0) {
            this <- do.call(rbind, lapply(pidx, function(z) { out <- as.data.frame(x$iwc[[z]]$plotargs$x); out$id <- z; out}))
            names(this) <- c("x", "y", "id")
            out$iwc <- list(as_plotter(plotfun = "ggplot2::geom_path", plotargs = list(data = this, aes_string(x = "x", y = "y", group = "id"), col = x$iwc[[pidx[1]]]$plotargs$col, inherit.aes = FALSE)))
        }
        if (!is.null(x$iwc$labels)) {
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$iwc$labels$plotargs$x)))
            out$iwc <- c(out$iwc, list(as_plotter(plotfun = "ggplot2::geom_sf_text", plotargs = list(data = as.data.frame(this), aes_string(label = "a.1"), parse = FALSE, col = x$iwc$labels$plotargs$col, size = 2, inherit.aes = FALSE))))
        }
        out$plot_sequence <- c(out$plot_sequence, "iwc")
    }

    if (!is.null(x$research_blocks)) {
        if (is.null(x$research_blocks$plotargs$col)) x$research_blocks$plotargs$col <- NA
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$research_blocks$plotargs$x)))
        out$research_blocks <- list(as_plotter(plotfun = "ggplot2::geom_sf", plotargs = list(data = this, col = x$research_blocks$plotargs$border, fill = x$research_blocks$plotargs$col, inherit.aes = FALSE)))
        if (!is.null(x$research_blocks$labels)) {
            this <- x$research_blocks$labels$plotargs$x
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(this)))
            out$research_blocks <- c(out$research_blocks, list(as_plotter(plotfun = "ggplot2::geom_sf_text", plotargs = list(data = as.data.frame(this), aes_string(label = as.character("GAR_Short_")), parse = FALSE, col = x$research_blocks$labels$plotargs$col, size = 2, inherit.aes = FALSE))))
        }
        out$plot_sequence <- c(out$plot_sequence, "research_blocks")
    }


    if (!is.null(x$sprfmo_research_blocks)) {
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$sprfmo_research_blocks[[1]]$plotargs$x)))
        that <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$sprfmo_research_blocks[[2]]$plotargs$x)))
        out$sprfmo_research_blocks <- list(as_plotter(plotfun = "ggplot2::geom_sf", plotargs = list(data = this, col = x$sprfmo_research_blocks[[1]]$plotargs$col,  inherit.aes = FALSE)),
                                           as_plotter(plotfun = "ggplot2::geom_sf", plotargs = list(data = that, col = x$sprfmo_research_blocks[[2]]$plotargs$col,  inherit.aes = FALSE)))
        out$plot_sequence <- c(out$plot_sequence, "sprfmo_research_blocks")
    }

    if (!is.null(x$eez)) {
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$eez$plotargs$x)))
        out$eez <- list(as_plotter(plotfun = "ggplot2::geom_sf", plotargs = list(data = this, col = x$eez$plotargs$border, fill = x$eez$plotargs$col, inherit.aes = FALSE)))
        if (!is.null(x$eez$labels)) {
            this <- x$eez$labels$plotargs$x
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(this)))
            out$eez <- c(out$eez, list(as_plotter(plotfun = "ggplot2::geom_sf_text", plotargs = list(data = this, aes_string(label = "ShortLabel"), parse = FALSE,size = 2, col = x$eez$labels$plotargs$col, inherit.aes = FALSE))))##, cex = x$eez$labels$cex, pos = x$eez$labels$pos, offset = x$eez$labels$offset)
        }
        out$plot_sequence <- c(out$plot_sequence, "eez")
    }

    if (!is.null(x$mpa)) {
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$mpa$plotargs$x)))
        out$mpa <- list(as_plotter(plotfun = "ggplot2::geom_sf", plotargs = list(data = this, col = x$mpa$plotargs$border, fill = x$mpa$plotargs$col, inherit.aes = FALSE)))
        if (!is.null(x$mpa$labels)) {
            this <- x$mpa$labels$plotargs$x
            this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(this)))
            out$mpa <- c(out$mpa, list(as_plotter(plotfun = "ggplot2::geom_sf_text", plotargs = list(data = as.data.frame(this), aes_string(label = "ShortLabel"), parse = TRUE, col = x$mpa$labels$plotargs$col, size = 2, inherit.aes = FALSE))))##, cex = x$mpa$labels$cex, pos = x$mpa$labels$pos, offset = x$mpa$labels$offset)
        }
        out$plot_sequence <- c(out$plot_sequence, "mpa")
    }

    if (!is.null(x$ccamlr_planning_domains)) {
        this <- suppressWarnings(sf::st_intersection(buf, sf::st_as_sf(x$ccamlr_planning_domains$plotargs$x)))
        ## TODO fix that intersection, is slow because of complexity of coastline
        out$ccamlr_planning_domains <- list(as_plotter(plotfun = "ggplot2::geom_sf", plotargs = list(data = this, col = x$ccamlr_planning_domains$plotargs$border, fill = x$ccamlr_planning_domains$plotargs$col, inherit.aes = FALSE)))
        if (!is.null(x$ccamlr_planning_domains$labels)) {
            ## this is horrible code
            crds <- as.data.frame(sp::coordinates(x$ccamlr_planning_domains$labels[[1]]$plotargs$x))
            names(crds) <- c("x", "y")
            crds$lab <- x$ccamlr_planning_domains$labels[[1]]$plotargs$x$labs
            out$ccamlr_planning_domains <- c(out$ccamlr_planning_domains, list(as_plotter(plotfun = "ggplot2::geom_text", plotargs = list(data = crds, aes_string(x = "x", y = "y", label = "lab"), parse = FALSE, col = x$ccamlr_planning_domains$labels[[1]]$plotargs$col, inherit.aes = FALSE, hjust = 0.5, vjust = 1))))
            crds$lab <- x$ccamlr_planning_domains$labels[[2]]$plotargs$x$labs1
            out$ccamlr_planning_domains <- c(out$ccamlr_planning_domains, list(as_plotter(plotfun = "ggplot2::geom_text", plotargs = list(data = crds, aes_string(x = "x", y = "y", label = "lab"), parse = FALSE, col = x$ccamlr_planning_domains$labels[[2]]$plotargs$col, inherit.aes = FALSE, hjust = 0.5, vjust = 0))))
            crds$lab <- x$ccamlr_planning_domains$labels[[3]]$plotargs$x$labs2
            out$ccamlr_planning_domains <- c(out$ccamlr_planning_domains, list(as_plotter(plotfun = "ggplot2::geom_text", plotargs = list(data = crds, aes_string(x = "x", y = "y", label = "lab"), parse = FALSE, col = x$ccamlr_planning_domains$labels[[3]]$plotargs$col, inherit.aes = FALSE, hjust = 0.5, vjust = 1))))
            crds$lab <- x$ccamlr_planning_domains$labels[[4]]$plotargs$x$labs7
            out$ccamlr_planning_domains <- c(out$ccamlr_planning_domains, list(as_plotter(plotfun = "ggplot2::geom_text", plotargs = list(data = crds, aes_string(x = "x", y = "y", label = "lab"), parse = FALSE, col = x$ccamlr_planning_domains$labels[[4]]$plotargs$col, inherit.aes = FALSE, hjust = 0, vjust = 0.5))))
            ## the hjust/vjust settings here are a rough attempt to position the labels more nicely
            ## needs work
        }
        out$plot_sequence <- c(out$plot_sequence, "ccamlr_planning_domains")
    }

    if (!is.null(x$border)) {
        suppressMessages(this <- fortify(x$border$plotargs$x))
        this$col <- (as.numeric(this$id) %% length(x$border$plotargs$col)) + 1
        out$border <- NULL
        for (ii in seq_along(x$border$plotargs$col)) {
            out$border <- c(out$border, list(as_plotter(plotfun = "ggplot2::geom_polygon", plotargs = list(data = this[this$col == ii, ], aes_string(x = "long", y = "lat", group = "group"), fill = x$border$plotargs$col[ii], col = "black"))))
        }
        out$plot_sequence <- c(out$plot_sequence, "border")
    }
    return(structure(out, class = "SOggmap"))
}

#' @method plot SOggmap
#' @export
plot.SOggmap <- function (x, y, ...) {
    print(x)
}

#' @method print SOggmap
#' @export
print.SOggmap <- function(x, ...) {
    print(plot_all_gg(x))
}

## iterate through the object's plot_sequence vector, running the plotfun with plotargs for each
plot_all_gg <- function(x) {
    assert_that(inherits(x, c("SOggmap")))
    ## interate through each plottable element in turn
    p <- NULL
    for (toplot in intersect(x$plot_sequence, names(x))) {
        allpf <- x[[toplot]] ## all the stuff to plot for this element
        ## either a SO_plotter object, or a list thereof
        ## if it's just one, put it in a list
        if (inherits(allpf, "SO_plotter")) allpf <- list(allpf)
        if (!all(vapply(allpf, inherits, "SO_plotter", FUN.VALUE = TRUE))) {
            warning("plotting behaviour for '", toplot, "' should be specified by an SO_plotter object or list of such objects, ignoring")
            next
        }
        ## evaluate each of these plotfuns
        for (thispf in allpf[seq_along(allpf)]) {
            thisfun <- thispf$plotfun
            this_plotargs <- thispf$plotargs
            thisp <- if (is.character(thisfun)) do.call(eval(parse(text = thisfun)), this_plotargs) else do.call(thisfun, this_plotargs)
            p <- if (is.null(p)) thisp else p + thisp
        }
        ##if (!is.null(thispf$labels)) {
        ##    allpf <- thispf$labels ## all the stuff to plot for this element
        ##    if (is.list(allpf) && length(allpf) > 1 && is.null(names(allpf))) {
        ##        ## a list of plotfun/args to iterate over
        ##    } else {
        ##        allpf <- list(allpf)
        ##    }
        ##    for (thispf in allpf) {
        ##        thisfun <- thispf$plotfun
        ##        this_plotargs <- thispf$plotargs
        ##        if (is.character(thisfun)) do.call(eval(parse(text = thisfun)), this_plotargs) else do.call(thisfun, this_plotargs)
        ##    }
        ##}
    }
    p
}
